### ISSUE TITLE
MissingTemporaryURLKey

### ISSUE THREAD

**Issue by krestaino** [216software/ajax-put-rackspace#5]
Hello! I'm having an issue running `python apr.py YOUR_RACKSPACE_USER_NAME YOUR_API_KEY`

`Traceback (most recent call last):
  File "apr.py", line 82, in <module>
    uploads_container, filename, 60*60, method='PUT')
  File "/usr/local/lib/python2.7/site-packages/pyrax/object_storage.py", line 2384, in get_temp_url
    method=method, key=key, cached=cached)
  File "/usr/local/lib/python2.7/site-packages/pyrax/object_storage.py", line 1108, in get_temp_url
    raise exc.MissingTemporaryURLKey("You must set the key for "
pyrax.exceptions.MissingTemporaryURLKey: You must set the key for Temporary URLs before you can generate them. This is done via the set_temp_url_key() method.`

Any idea? I'm not familiar with Python or Pyrax so I may be doing something obviously wrong.

**Comment by mw44118** [comment]
Hi Kevin!

One thing -- you need to replace the text "YOUR_RACKSPACE_USER_NAME" with
whatever your rackspace user name is.  Same thing with YOUR_API_KEY.

Did you do that?

**Comment by krestaino** [comment]
Yup! I did both. I noticed the container is created on Rackspace, so it seems it is authenticating correctly.

**Comment by mw44118** [comment]
There is a one-time action of setting the tenp URL key.  Maybe I forgot to
describe how to do that.

**Comment by krestaino** [comment]
What is that action? I'm not sure I see it in the documentation. Any help would be greatly appreciated!

**Comment by krestaino** [comment]
@mw44118 Any idea what that one-time action of setting the temp URL key is?
